del *.OBJ
del *.ABS
asm68k -I ../inc COM_OPE.SRC
asm68k -I ../inc DEF2_1P.SRC
asm68k -I ../inc DEF2_2P.SRC
asm68k -I ../inc DEF_1P.SRC
asm68k -I ../inc DEF_2P.SRC
asm68k -I ../inc EM1_TBL.SRC
asm68k -I ../inc EM2_TBL.SRC
asm68k -I ../inc EM3_TBL.SRC
asm68k -I ../inc EM4_TBL.SRC
asm68k -I ../inc EM5_TBL.SRC
asm68k -I ../inc EM6_TBL.SRC
asm68k -I ../inc EM7_TBL.SRC
asm68k -I ../inc EM8_TBL.SRC
asm68k -I ../inc EMH_SCLI.SRC
asm68k -I ../inc EM_BACK.SRC
asm68k -I ../inc EM_DATA.SRC
asm68k -I ../inc EM_FRONT.SRC
asm68k -I ../inc EM_P1.SRC
asm68k -I ../inc EM_P2.SRC
asm68k -I ../inc EM_PACK.SRC
asm68k -I ../inc EM_SCLIM.SRC
asm68k -I ../inc EM_SP1.SRC
asm68k -I ../inc EM_SP10.SRC
asm68k -I ../inc EM_SP10H.SRC
asm68k -I ../inc EM_SP11.SRC
asm68k -I ../inc EM_SP11H.SRC
asm68k -I ../inc EM_SP1H.SRC
asm68k -I ../inc EM_SP2.SRC
asm68k -I ../inc EM_SP2H.SRC
asm68k -I ../inc EM_SP3.SRC
asm68k -I ../inc EM_SP3H.SRC
asm68k -I ../inc EM_SP4.SRC
asm68k -I ../inc EM_SP4H.SRC
asm68k -I ../inc EM_SP5.SRC
asm68k -I ../inc EM_SP5H.SRC
asm68k -I ../inc EM_SP6.SRC
asm68k -I ../inc EM_SP6H.SRC
asm68k -I ../inc EM_SP7.SRC
asm68k -I ../inc EM_SP7H.SRC
asm68k -I ../inc EM_SP8.SRC
asm68k -I ../inc EM_SP8H.SRC
asm68k -I ../inc EM_SP9.SRC
asm68k -I ../inc EM_SP9H.SRC
asm68k -I ../inc GAME_SYM.SRC
asm68k -I ../inc HK3.SRC
asm68k -I ../inc HK3_INT.SRC
asm68k -I ../inc HK3_SET.SRC
asm68k -I ../inc HK3_SUB.SRC
asm68k -I ../inc HK3_TBL.SRC
asm68k -I ../inc MOTION.SRC
asm68k -I ../inc NEWS.SRC
asm68k -I ../inc STATE_CH.SRC
lnk68k -c HK3.CMD -m > HK3.MAP
copy *.abs ..\bin
