#!/bin/bash

sed -i -e "s/___2___/ACCUEILLEZ UN NOUVEAU CHALLENGER/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___3___/ L''ECRAN CHANGE POUR LE VERSUS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___4___/IL N''Y A PLUS DE CHALLENGERS./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___5___/ON RETOURNE SUR LE MODE HISTOIRE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___6___/DEFAIT PAR/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___7___/DEFAIT PAR/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___8___/TU N''ES PAS AUTORISE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___9___/ESSAYE ENCORE \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___10___/JE NE SAIS PAS OU ELLE EST./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___11___/JACK AU \"MACS BAR\" DOIT/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___12___/SAVOIR./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___13___/REVIENS QUAND TU VEUX./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___14___/JE TE DONNERAI UNE BONNE LECON./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___15___/ECOUTE, ON NE FERA JAMAIS DE MAL/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___16___/ A UNE FEMME OU A UN GOSSE./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___17___/JE PENSE QUE J''AI VU/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___18___/CETTE FILLE A CHINA TOWN./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___19___/AH AH AH###AH AH/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___20___/AH\! AH\! AH\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___21___/VA AU RESTAURANT \"LAMOR\"/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___22___/LE VIDEUR DOIT SAVOIR CA./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___23___/MAINTENANT TU COMPRENDS./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___24___/NE ME JUGE PAS A MON APPARENCE /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___25___/TU ES TOUJOURS GATE###/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___26___/DETENDS TOI BABY \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___27___/J''Y CROIS PAS \! J''AI PERDU \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___28___/JE TE DIRAI TOUT CE QUE JE SAIS./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___29___/YURI EST DANS LA BASE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___30___/MILITAIRE MAIS###/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___31___/PERSONNE NE PEUT Y RENTRER/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___32___/EXCEPTE MICKY/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___33___/J''Y CROIS PAS \! J''AI PERDU \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___34___/JE SAIS QUE YURI EST DANS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___35___/CETTE BASE MILITAIRE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___36___/MICKY DOWNTOWN EST LE SEUL/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___37___/A POUVOIR Y RENTRER/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___38___/NE VA JAMAIS LA-BAS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___39___/JE PEUX T''AMENER AU PORT MAIS /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___40___/PAS DANS LE CARGO/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___41___/BIEN C''EST CA /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___42___/TU POURRAS RENCONTRER MON PATRON/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___43___/DANS CETTE USINE./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___44___/TU SAIS, A PROPOS DE YURI,/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___45___/ELLE EST BIENTOT DEVANT LES/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___46___/PORTES DU PARADIS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___47___/TROUVE LE DOJO DE KARATE PRES DU/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___48___/PORT. UN MEC PUISSANT T''ATTEND./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___49___/SAUF SI TU MAITRISES LE HAOW-KEN/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___50___/TU NE POURRAS JAMAIS ME BATTRE./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___51___/ARRETE RYO \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___52___/ARRETE ROBERT \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___53___/YURI TU VAS BIEN ?/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___54___/JE M''INQUIETAIS POUR TOI/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___55___/YURI \!\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___56___/OUI JE VAIS BIEN./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___57___/ECOUTE MOI RYO/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___58___/CET HOMME EST NOTRE###/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___59___/QUOI ? QU''EST-CE QUE TU AS DIT ?/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___60___/POURQUOI CA?/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___61___/YURI###/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___62___/YURI### TU PEUX/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___63___/COMPTER SUR MOI./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___64___/QUEL MEC/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___65___/BALEZE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___66___/JE DOIS AMELIORER/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___67___/MES COMPETENCES./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___68___/DERNIERE ETAPE./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___69___/JE DEFONCERAI N''IMPORTE QUEL/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___70___/MEC DANS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___71___/CETTE VILLE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___72___/COMBATTRE UN HOMME/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___73___/AVEC UNE ARME./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___74___/JE DOIS UTILISER LE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___75___/HAOW-KEN/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___76___/QU''IMPORTE QUI/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___77___/SE MONTRERA/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___78___/JE LE BATTRAI/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___79___/AVEC MA PUISSANCE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___80___/ATTEND \!\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___81___/YURI \!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___82___/DOIS-JE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___83___/ENCORE ME BATTRE ?/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___84___/QUE LES CHOSES/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___85___/SERIEUSES COMMENCENT\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___86___/VAURIENS/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___87___/QUE LE COMBAT COMMENCE\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___88___/J''ESPERE QUE YURI /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___89___/VA BIEN/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___90___/ILS DISENT QUE C''EST/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___91___/UN GRAND MAITRE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___92___/L''ESPRIT DANS LA/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___93___/ZONE MILITAIRE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___94___/SI JAMAIS UN TEL MAITRE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___95___/EXISTE./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___96___/JE VAIS LE/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___97___/PULVERISER/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___98___/QU''EST-CE QUE?\! TU ES /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___99___/DE L''HISTOIRE ANCIENNE MEC\!/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___100___/RYO SAKAZAKI, POUR RETROUVER SA/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___101___/SOEUR KIDNAPPEE, DESCEND DANS LA/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___102___/DANGEREUSE VILLE DE SOUTH TOWN./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___103___/ROBERT GARCIA, UN AMI/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___104___/ET RIVAL DE RYO, DESCEND /g" LANG2__TEMPLATE.SRC
sed -i -e "s/___105___/DANS SOUTH TOWN AVEC LUI./g" LANG2__TEMPLATE.SRC
sed -i -e "s/___106___/QUI LES ATTENDS A/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___107___/SOUTH TOWN ?/g" LANG2__TEMPLATE.SRC
sed -i -e "s/___108___/YURI, MA SOEUR,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___109___/DOIT BIEN ALLER./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___110___/JE TE DEMASQUERAI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___111___/---/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___112___/HMM\! QUI EST/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___113___/INVINCIBLE?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___114___/C''EST UNE BLAGUE DE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___115___/REVETIR UN MASQUE DE GENIE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___116___/ALLER \!\!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___117___/ALLER\!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___118___/JE VAIS TE DEFONCER/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___119___/TU ES UN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___120___/ESPION DE LA POLICE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___121___/TU ES MICKY \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___122___/TU SAIS POURQUOI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___123___/JE SUIS LA,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___124___/N''EST-CE PAS?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___125___/HE TOI \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___126___/LE MESSAGER/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___127___/RAMENES TES FESSES/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___128___/PAR ICI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___129___/HE NE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___130___/ME SOUS ESTIME PAS/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___131___/DEGAGE DE MA/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___132___/VUE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___133___/OU ES LE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___134___/VIDEUR ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___135___/DEGAGES DE LA\!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___136___/AMENE MOI LE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___137___/VIDEUR/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___138___/BONSOIR,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___139___/MONSIEUR./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___140___/TU ES L''UN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___141___/D''ENTRE EUX NON ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___142___/TU NE VEUX PAS/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___143___/ME PARLER ? TRES BIEN./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___144___/WOW \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___145___/FAIS GAFFE \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___146___/T''AS PAS/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___147___/L''AIR D''ALLER BIEN./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___148___/AH##AH, AH,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___149___/AH, AH, AH, AH,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___150___/QU''EST CE QUE TU/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___151___/VEUX GAMIN ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___152___/MONTRE DU RESPECT,/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___153___/DIS \"S''IL TE PLAIT\"./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___154___/T''AS COMPRIS GAMIN ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___155___/DONC TU ES JACK/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___156___/T''ES UN VRAI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___157___/RIGOLO \!\!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___158___/C''EST POUR MOI \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___159___/DEMANDE LUI AVEC/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___160___/TA FORCE \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___161___/HE MONSIEUR \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___162___/OU EST YURI ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___163___/DIS MOI OU/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___164___/EST MA SOEUR \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___165___/HMM###/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___166___/IL EST LA./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___167___/BOUTON A POUR DONNER UN COUP DE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___168___/POING/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___169___/BOUTON B POUR DONNER UN COUP DE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___170___/PIED/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___171___/APPUYEZ SUR A PUIS SUR C/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___172___/POUR UN COUP DE POING FORT./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___173___/APPUYEZ SUR A PUIS SUR B/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___174___/POUR FAIRE UN COUP DE PIED FORT./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___175___/BOUGEZ LE JOYSTICK POUR SAUTER/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___176___/LA GARDE C''EST ARRIERE \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___177___//g" LANG3__TEMPLATE.SRC
sed -i -e "s/___178___/AGGRIPEZ L''ENNEMI ET APPUYEZ/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___179___/SUR C POUR LE PROJETER \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___180___/RESTEZ APPUYE SUR A/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___181___/POUR REMONTER SON ESPRIT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___182___/BOUGEZ LE JOYSTICK + A/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___183___/POUR FAIRE UN PUISSANT UPPERCUT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___184___/SAUTE DANS LE DOS ET APPUIE SUR/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___185___/C POUR UN COUP DE PIED RETOURNE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___186___/APPUYEZ SUR C PENDANT UN SAUT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___187___/POUR SAUTER DU BORD DE L''ECRAN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___188___/APPUYER SUR C ET B POUR UN COUP/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___189___/DE PIED LEGER ET METTRE AU SOL/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___190___/BOUTON D POUR PROVOQUER L''ENNEMI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___191___/REGARDE ET ATTAQUE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___192___/UTILISEZ LE TEMPS/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___193___/UTILISE LE JOYSTICK POUR CHOISIR/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___194___/LE BONUS GAME ET APPUYEZ SUR A/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___195___/BRISE DES BOUTEILLES/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___196___/ATTEND LE BON MOMENT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___197___/APPUIE SUR A POUR FRAPPER/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___198___/L''ESPRIT DE RYO SAKAZAKI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___199___/A AUGMENTE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___200___/L''ESPRIT DE ROBERT GARCIA/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___201___/GAGNE DE LA FORCE EN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___202___/DETRUISANT LE PILLIER DE GLACE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___203___/APPUIE SUR LE BOUTON RAPIDEMENT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___204___/GAGNE DE LA PUISSANCE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___205___/L''ENERGIE DE RYO SAKAZAKI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___206___/L''ENERGIE DE ROBERT GARCIA/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___207___/FAIS 10 \"HAOW-KEN\" POUR/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___208___/ETRE TOUCHE PAR LA LUMIERE./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___209___/JOYSTICK        + BOUTON A/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___210___/POUR LE COUP SPECIAL HAOW-KEN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___211___/RYO SAKAZAKI MAITRISE LE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___212___/ROBERT GARCIA MAITRISE LE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___213___/COUP SPECIAL \"HAOW-KEN\"/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___214___/ROBERT GARCIA A RATE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___215___/ROBERT GARCIA A RATE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___216___/L''ENTRAINEMENT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___217___/JOYSTICK        + BOUTON A/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___218___/POUR LE COUP SPECIAL KOOH-KEN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___219___/POUR LE COUP SPECIAL RYUGEKI-KEN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___220___/JOYSTICK        + BOUTON C/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___221___/POUR LE COUP SPECIAL ZANRETSUKEN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___222___/POUR LE COUP SPECIAL GENEI-KICK/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___223___/JOYSTICK        + BOUTON B/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___224___/POUR FAIRE LE HIENSHIPUKICK/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___225___/CROISE ENCORE MON CHEMIN/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___226___/ ET TU SERA A MOI \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___227___/JE TE PRENDS N'IMPORTE QUAND /g" LANG3__TEMPLATE.SRC
sed -i -e "s/___228___/LE SOUFFLE DE TACO \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___229___/PRESONNE N'EST PLUS FORT QUE MOI/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___230___/QUELLE DECEPTION \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___231___/TAKE ON, MOI?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___232___/JE VAIS VOUS EMPORTER \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___233___/YEE HEE HEE/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___234___/QUI EST LE SUIVANT ?/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___235___/VIENS LA, DEBILE./g" LANG3__TEMPLATE.SRC
sed -i -e "s/___236___/JE VAIS TE MONTRER MON TRUC /g" LANG3__TEMPLATE.SRC
sed -i -e "s/___237___/AH ! QUI EST EST LE SUIVANT/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___238___/ QUE JE LUI BRISE LES COUILLES \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___239___/QU''EST CE TU REGARDES ? TU VEUX/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___240___/COMMENCER, ALLONS-Y \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___241___/QUELLE POULE MOUILEE \! J''AI MEME/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___242___/PAS TRANSPIRE \! SUIVANT \!/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___243___/RAMENE-TOI \! JE VAIS GUERIR TA/g" LANG3__TEMPLATE.SRC
sed -i -e "s/___244___/ MALADIE QU''ON APPELLE LA VIE./g" LANG3__TEMPLATE.SRC

cp LANG2__TEMPLATE.SRC LANG2.SRC
cp LANG3__TEMPLATE.SRC LANG3.SRC

git checkout LANG2__TEMPLATE.SRC
git checkout LANG3__TEMPLATE.SRC

cp LANG2.SRC ../compilable/AOF/lang
cp LANG3.SRC ../compilable/AOF/lang